all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/takuya-go-kit/go-logkit:
    interfaces:
      Logger:
        config:
          dir: "mock"
          filename: "Logger.go"
          pkgname: "mock"
          structname: "MockLogger"
